"""Wire action spec: validation, packaging on disk, and the deterministic test."""

from __future__ import annotations

import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

import jsonschema

from . import config

PARAM_TYPES = {"string", "integer", "number", "boolean"}
ACTION_ID_RE = re.compile(r"^[a-z0-9]+(_[a-z0-9]+)+$")

TEST_TEMPLATE = '''"""Auto-generated by Wire Forge. Runs the action live and checks its return schema."""

import json
from pathlib import Path

import jsonschema

from wireforge.spec import run_action

HERE = Path(__file__).parent


def test_{action_id}():
    spec = json.loads((HERE / "spec.json").read_text(encoding="utf-8"))
    params = json.loads((HERE / "test_params.json").read_text(encoding="utf-8"))
    out = run_action(HERE / "action.py", params)
    assert out["ok"], out.get("error")
    jsonschema.validate(out["result"], spec["return_schema"])
'''


def validate_spec(spec: dict) -> list[str]:
    errs = []
    if not ACTION_ID_RE.match(spec.get("action_id", "")):
        errs.append("action_id must be snake_case like 'site_action_name'")
    if spec.get("type") not in ("read", "write"):
        errs.append("type must be 'read' or 'write'")
    for p in spec.get("parameters", []):
        if p.get("type") not in PARAM_TYPES:
            errs.append(f"parameter {p.get('name')!r}: type must be one of {sorted(PARAM_TYPES)}")
        for k in ("name", "description"):
            if not p.get(k):
                errs.append(f"parameter missing {k!r}")
    try:
        jsonschema.Draft202012Validator.check_schema(spec.get("return_schema", {}))
    except jsonschema.SchemaError as exc:
        errs.append(f"return_schema is not valid JSON Schema: {exc.message}")
    if not spec.get("return_schema", {}).get("required"):
        errs.append("return_schema must list required fields, or the test proves nothing")
    return errs


def run_action(action_path: Path, params: dict) -> dict:
    with tempfile.TemporaryDirectory() as tmp:
        pfile, ofile = Path(tmp) / "params.json", Path(tmp) / "out.json"
        pfile.write_text(json.dumps(params), encoding="utf-8")
        try:
            proc = subprocess.run(
                [sys.executable, "-m", "wireforge.harness", str(action_path), str(pfile), str(ofile)],
                cwd=config.ROOT, capture_output=True, text=True, timeout=config.ACTION_TIMEOUT_S,
            )
        except subprocess.TimeoutExpired:
            return {"ok": False, "error": f"timed out after {config.ACTION_TIMEOUT_S}s"}
        if not ofile.exists():
            return {"ok": False, "error": "harness crashed", "stderr": proc.stderr[-2000:]}
        return json.loads(ofile.read_text(encoding="utf-8"))


def check_output(spec: dict, out: dict) -> list[str]:
    if not out.get("ok"):
        return [f"action raised: {out.get('error')}\n{out.get('traceback', '')}"]
    try:
        jsonschema.validate(out["result"], spec["return_schema"])
    except jsonschema.ValidationError as exc:
        return [f"output violates return_schema at {list(exc.absolute_path)}: {exc.message}"]
    return []


def package(out_dir: Path, spec: dict, code: str, test_params: dict) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    wire_spec = {
        "action_id": spec["action_id"],
        "name": spec["name"],
        "description": spec["description"],
        "tags": spec.get("tags", []),
        "type": spec["type"],
        "mode": "async",
        "auth_mode": "none",
        "auth_required": False,
        "parameters": spec["parameters"],
        "return_schema": spec["return_schema"],
        "source_url": spec.get("source_url"),
        "endpoints": spec.get("endpoints", []),
    }
    (out_dir / "spec.json").write_text(json.dumps(wire_spec, indent=2), encoding="utf-8")
    (out_dir / "action.py").write_text(code, encoding="utf-8")
    (out_dir / "test_params.json").write_text(json.dumps(test_params, indent=2), encoding="utf-8")
    (out_dir / "test_action.py").write_text(TEST_TEMPLATE.format(action_id=spec["action_id"]), encoding="utf-8")
    return out_dir
